name: Build the stuff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: ["published"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: push-to-ghcr
      uses: macbre/push-to-ghcr@v12
      with:  
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
